### PR TITLE
WIP: Implementing backup and restore feature

### PR DESCRIPTION
**Pull request by frenos**
# Proposed Feature:
The admin user should be able to easily export all the documents with their respective metadata. Later he should be able to import the documents again. Short: A general backup and restore feature.

To first introduce this feature and because of changing UI in the near future I propose to start off with two custom manage.py commands. One allows you to backup everything to an archive, another one allows you to restore everything from such an archive.

# Planned Implementation Detail:
We not only need the original document itself but also the metadata. For this I propose to create a backup.json that contains these information about all the documents in the current backup.

Imagine this structure in papermerge:
<pre>
#root
|---receipts
|  |----aldi.pdf
|  |----lidl.pdf
|---letters
   |----bank1.pdf
   |----bank2.pdf
</pre>

The backup-archive will have the same relative structure and additionally contain a file `backup.json` in the root.
This file has a few meta-keys at the start and then contains a list of documents.
Example:
```javascript
{
  "version": "1.3.0",
  "created": "11.07.20 06:55",
  
  "documents": [
    {
      'path': 'receipts/aldi.pdf',
      'language': 'deu',
      'notes': "This is a receipt",
    },
        {
      'path': 'receipts/lidl.pdf',
      'language': 'deu',
      'notes': "This is also a receipt",
    }
    ...
  ]
}
```
The top-level keys are required, for the document-obj only the path is required. All other keys that are not set use the default value (e.g. empty string). Further keys that are set and not understood by the restore are ignored. That creates a certain backwards compatibility. Think for example papermerge supports tags in the future and you export them, then you can still import that in to the current version and at least get the features supported now working.

# Todo:
- [x] Export documents to archive
- [x] Create backup.json and add to archive
- [x] Import documents from archive
- [ ] Documentation

# Future perspective:
I will try to make this first implementation as generic and plugable as possible. In the future we could improve by making it work in the worker and add it to the UI.

### CODE REVIEW

**Comment by ciur** [comment]
oh, man, it is little bit more complicated than you think :)
First of all, the way you describe the feature requests - discards the OCR information. If no OCR info is included - then user will need to reOCR again everything after import. For 2000 documents this will take a while!

Now I know what you are thinking... you probably would say - "sure, just include ocr related fields in backup.json!" - which sounds very sane to me. But again, not that simple :)

Besides obvious documents/metadata info, Papermerge stores extracted OCRed text, per page for every version of the document (yes, internally it supports vesioning which make docs non destructive - even of you cut/paste pages around) ! Have a look at media folder (results subfolder) and you will understand what I mean.

Anyway, feature is not that complex to implement and I will definitely implement it in 1.4 release, because it will ease 1.2 -> 1.4 migration.

Again, thank you for great Feature Request/Pull Request/Feedback!

**Comment by frenos** [comment]
oha, looks like in the week I have been using papermerge I have only gradually scratched the surface of features :).
My NAS is quite powerful and can churn through a lot of tesseract without it becoming a big annoyance so I was under the impression it would be enough to just backup the data the user created/upload and generate everything anew.
But you are right, seeing as there is a request for raspberry pi ARM images there should be a trade-off between simplicity of backup and processing power needed.

In this MR I would implement Mode 2, only exporting the documents and their folder structure in papermerge. As versioning is not exposed in the UI I think the best way currently is to use the latest version. The backup contains what the user sees in the webinterface.

I will try to get it done over the weekend and leave Mode1 to your experience then :P

**Comment by ciur** [comment]
hey man, I saw your changes. Thank you so much for contribution!

Besides django command - for me it makes sense to have UI for backups/restore. But don't worry at all about UI, I will take care of that part (when clicking create backup, a celery job will be created. When done - a download url to backup will be displayed).

**Comment by frenos** [comment]
Yes, I was hoping you could integrate it into the UI in the future. The functions should be so general that you can call them from anywhere as long as you give the a file-like object where the result should be written.

Should I still write documentation for the management command or do you want to hide it until it's in the UI?

**Comment by ciur** [comment]
Don't bother with documentation. I will write docs. I will add couple of minor changes in your code (e.g. I think triggering an OCR during update must be optional/provided by command args).

Outstanding work, I am impressed! Basically you figured out how to use internal (not documented) API.
Your work will be part of 1.4.0.
Thank you again!

**Comment by frenos** [comment]
I merged your latest commits from master and solved the conflict. As you wanted to document yourself I'll see this finished from my side. You also should have access to branch to change code as you seem fit.

Actually your code was written well so I didn't need much documentation for the internal stuff.

**Comment by ciur** [comment]
Outstanding work, man! Thank you!

Documentation and UI part will follow.

**Pull request merged**
